[2024-09-23T18:06:59.676+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:06:57.815384+00:00 [queued]>
[2024-09-23T18:06:59.693+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:06:57.815384+00:00 [queued]>
[2024-09-23T18:06:59.694+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:06:59.696+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-09-23T18:06:59.697+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:06:59.720+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-09-23 18:06:57.815384+00:00
[2024-09-23T18:06:59.729+0000] {standard_task_runner.py:55} INFO - Started process 14623 to run task
[2024-09-23T18:06:59.735+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-09-23T18:06:57.815384+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp6kkcuh7n']
[2024-09-23T18:06:59.740+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask is_api_available
[2024-09-23T18:06:59.821+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:06:57.815384+00:00 [running]> on host 3faff16bae04
[2024-09-23T18:06:59.939+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T18:06:57.815384+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T18:06:57.815384+00:00
[2024-09-23T18:06:59.942+0000] {http.py:120} INFO - Poking: api/
[2024-09-23T18:06:59.960+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-09-23T18:06:59.963+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-09-23T18:07:01.288+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-09-23T18:07:01.304+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240923T180657, start_date=20240923T180659, end_date=20240923T180701
[2024-09-23T18:07:01.366+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-09-23T18:07:01.402+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
