[2024-09-23T18:06:59.727+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2024-09-23T18:06:57.815384+00:00 [queued]>
[2024-09-23T18:06:59.746+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2024-09-23T18:06:57.815384+00:00 [queued]>
[2024-09-23T18:06:59.748+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:06:59.749+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-09-23T18:06:59.750+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:06:59.773+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-09-23 18:06:57.815384+00:00
[2024-09-23T18:06:59.784+0000] {standard_task_runner.py:55} INFO - Started process 14625 to run task
[2024-09-23T18:06:59.790+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2024-09-23T18:06:57.815384+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpxizvjzjj']
[2024-09-23T18:06:59.794+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask create_table
[2024-09-23T18:06:59.877+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2024-09-23T18:06:57.815384+00:00 [running]> on host 3faff16bae04
[2024-09-23T18:06:59.993+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T18:06:57.815384+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T18:06:57.815384+00:00
[2024-09-23T18:07:00.010+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-09-23T18:07:00.017+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2024-09-23T18:07:00.019+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-09-23T18:07:00.034+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20240923T180657, start_date=20240923T180659, end_date=20240923T180700
[2024-09-23T18:07:00.090+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-09-23T18:07:00.117+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
