[2024-09-23T18:07:10.546+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2024-09-23T18:07:08.828052+00:00 [queued]>
[2024-09-23T18:07:10.562+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2024-09-23T18:07:08.828052+00:00 [queued]>
[2024-09-23T18:07:10.563+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:07:10.564+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-09-23T18:07:10.565+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:07:10.592+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2024-09-23 18:07:08.828052+00:00
[2024-09-23T18:07:10.601+0000] {standard_task_runner.py:55} INFO - Started process 14645 to run task
[2024-09-23T18:07:10.607+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2024-09-23T18:07:08.828052+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpkjy9bsdl']
[2024-09-23T18:07:10.611+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask create_table
[2024-09-23T18:07:10.722+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2024-09-23T18:07:08.828052+00:00 [running]> on host 3faff16bae04
[2024-09-23T18:07:10.831+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T18:07:08.828052+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T18:07:08.828052+00:00
[2024-09-23T18:07:10.849+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2024-09-23T18:07:10.857+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2024-09-23T18:07:10.861+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2024-09-23T18:07:10.880+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20240923T180708, start_date=20240923T180710, end_date=20240923T180710
[2024-09-23T18:07:10.943+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-09-23T18:07:10.986+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
