[2024-09-23T18:07:10.594+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:07:08.828052+00:00 [queued]>
[2024-09-23T18:07:10.609+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:07:08.828052+00:00 [queued]>
[2024-09-23T18:07:10.611+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:07:10.612+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-09-23T18:07:10.615+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:07:10.637+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-09-23 18:07:08.828052+00:00
[2024-09-23T18:07:10.646+0000] {standard_task_runner.py:55} INFO - Started process 14647 to run task
[2024-09-23T18:07:10.653+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-09-23T18:07:08.828052+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppkmhp4wb']
[2024-09-23T18:07:10.657+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask is_api_available
[2024-09-23T18:07:10.773+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:07:08.828052+00:00 [running]> on host 3faff16bae04
[2024-09-23T18:07:10.886+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T18:07:08.828052+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T18:07:08.828052+00:00
[2024-09-23T18:07:10.888+0000] {http.py:120} INFO - Poking: api/
[2024-09-23T18:07:10.904+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-09-23T18:07:10.910+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-09-23T18:07:14.772+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-09-23T18:07:14.786+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240923T180708, start_date=20240923T180710, end_date=20240923T180714
[2024-09-23T18:07:14.818+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-09-23T18:07:14.863+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
