[2024-09-23T18:08:37.103+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:08:35.611089+00:00 [queued]>
[2024-09-23T18:08:37.128+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:08:35.611089+00:00 [queued]>
[2024-09-23T18:08:37.129+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:08:37.130+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-09-23T18:08:37.132+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-09-23T18:08:37.155+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-09-23 18:08:35.611089+00:00
[2024-09-23T18:08:37.164+0000] {standard_task_runner.py:55} INFO - Started process 14737 to run task
[2024-09-23T18:08:37.170+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2024-09-23T18:08:35.611089+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmppko3jrf7']
[2024-09-23T18:08:37.173+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask is_api_available
[2024-09-23T18:08:37.279+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2024-09-23T18:08:35.611089+00:00 [running]> on host 3faff16bae04
[2024-09-23T18:08:37.391+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-09-23T18:08:35.611089+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-23T18:08:35.611089+00:00
[2024-09-23T18:08:37.393+0000] {http.py:120} INFO - Poking: api/
[2024-09-23T18:08:37.408+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-09-23T18:08:37.411+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-09-23T18:08:37.712+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-09-23T18:08:37.736+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240923T180835, start_date=20240923T180837, end_date=20240923T180837
[2024-09-23T18:08:37.785+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-09-23T18:08:37.828+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
